# This file uses shared golangci-lint configuration from ecommerce-infrastructure
# 
# Base configuration: https://github.com/Sokol111/ecommerce-infrastructure/blob/master/configs/golangci/base.yml
# Service additions: https://github.com/Sokol111/ecommerce-infrastructure/blob/master/configs/golangci/service.yml
#
# Local file is used because golangci-lint doesn't support remote config extends yet.
# To update: copy from ecommerce-infrastructure/configs/golangci/

linters:
  enable:
    # Correctness
    - exhaustive
    - govet
    - errcheck
    - staticcheck
    
    # Code quality
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    
    # Best practices
    - errname
    - errorlint
    - nilnil
    - nilerr
    
    # Performance
    - prealloc
    - bodyclose
    
    # Security
    - gosec
    
    # Style
    - revive
    - stylecheck

linters-settings:
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
    check:
      - switch
      - map
    ignore-enum-types: ""
    explicit-exhaustive-switch: true
  
  errcheck:
    check-blank: true
    check-type-assertions: true
    
  govet:
    enable-all: true
    disable:
      - fieldalignment
    
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
  
  gosec:
    excludes:
      - G104
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - revive
    
    - path: ".*\\.gen\\.go$"
      linters:
        - all
    
    - path: vendor/
      linters:
        - all
    
    - path: internal/http/
      linters:
        - errcheck
      text: "Error return value of.*WriteHeader.*is not checked"
  
  exclude-dirs:
    - vendor
    - testdata
    - bin
    - mocks
  
  exclude-files:
    - ".*\\.gen\\.go$"
  
  new: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  concurrency: 4
