profile: coverage.out

threshold:
  total: 0

exclude:
  paths:
    - /cmd/
    - /db/migrations/
    - /internal/infrastructure/
    - /internal/testutil/
    - /mocks/
    - /test/
    - /module\.go$
    - main\.go$
