logger:
  level: "debug"

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  database: "image"
  replica-set: rs0
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "localhost:9092"
  consumers-config:
    group-id: "ecommerce-image-service"
    auto-offset-reset: "earliest"
    consumers:
      - handler: "productCreatedHandler"
        topic: "catalog.product.created.v1"

# kafka:
#   brokers: "kafka:29092"

observability:
  tracing-enabled: true
  metrics-enabled: false
  metrics-interval: 10s
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  prometheus-endpoint: "prometheus-server.observability.svc:9090"

application:
  presign-ttl: 15m # Presigned URL validity duration
  max-upload-bytes: 5242880 # 5 MB - maximum upload size

s3:
  endpoint: "http://minio:9000"
  region: "us-east-1"
  bucket: "products"
  access-key-id: "minioadmin"
  secret-key: "minioadmin123"
  use-path-style: true

imgproxy:
  base-url: "http://imgproxy:8080"
  key-hex: "0000000000000000000000000000000000000000000000000000000000000000"
  salt-hex: "1111111111111111111111111111111111111111111111111111111111111111"
