name: Release

on:
  push:
    branches:
      - master
    paths:
      - VERSION
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/build-and-release-go.yml@master
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
